spring:
  sql:
    init:
      platform: postgresql
  datasource:
    url: jdbc:postgresql://ec2-34-246-24-110.eu-west-1.compute.amazonaws.com:5432/dd3v31neh0oqjn
    username: xqeybnexpechse
    password: 08c6aa456a7f458e54b815460f3989c446bb4449537a2eaea0e005031c5a4b96
  jpa:
    hibernate:
      #      default_schema: public
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
